server:
  port: 8003

# mybatis配置
mybatis:
  # 本模块下的mapper配置文件类路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# spring配置
spring:
  application:
    #项目名
    name: springcloud-provider
  datasource:
    # 德鲁伊数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test3?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #修改Eureka上的默认描述信息
    instance-id: springcloud-provider-03

#info配置
info:
  app.name: ben-springcloud #项目的名称
  company.name: com.ben #公司的名称